add multinode strategy

diff --git a/provision.yml b/provision.yml
--- a/provision.yml
+++ b/provision.yml
@@ -269,6 +269,14 @@
     - name: OpenShift install
       shell: |
         set -exuo pipefail
+        NAME="mycluster"
+        CLUSTER_DIR="$${HOME}/clusters/$${NAME}"
+        INSTALL_DIR=${CLUSTER_DIR}
+        export BASE_DOMAIN=openshift.testing
+        export CLUSTER_NAME="$${NAME}"
+        CERT_ROTATION=${SNC_DISABLE_CERT_ROTATION:-enabled}
+        CRC_VM_NAME="$${NAME}"
+        OPENSHIFT_INSTALL="openshift-install"
         #sudo bash -c 'cat >> /etc/modprobe.d/kvm.conf' << EOF
         #options kvm_intel nested=1
         #EOF
@@ -279,26 +287,47 @@
         #sudo systemctl restart libvirtd
         # Set up iptables and firewalld
         # TODO: discover the ports
-        #sudo firewall-cmd --permanent --add-rich-rule "rule service name="libvirt" reject"
-        #sudo firewall-cmd --permanent --zone=libvirt --add-service=libvirt
-        #sudo firewall-cmd --zone=libvirt --add-service=libvirt --permanent
-        echo -e "[main]\ndns=dnsmasq" | sudo tee /etc/NetworkManager/conf.d/openshift.conf
-        echo server=/openshift.testing/192.168.126.1 | sudo tee /etc/NetworkManager/dnsmasq.d/openshift.conf
-        # Create new domain for ingress to make sure it able to resolve auth route URL
-        echo address=/.apps.openshift.testing/192.168.126.51 | sudo tee -a /etc/NetworkManager/dnsmasq.d/openshift.conf
-        sudo systemctl restart NetworkManager
-        #sudo timedatectl set-ntp off
-        #sudo date -s '-1 day'
+        sudo firewall-cmd --permanent --add-rich-rule "rule service name="libvirt" reject"
+        sudo firewall-cmd --permanent --zone=libvirt --add-service=libvirt
+        sudo firewall-cmd --zone=libvirt --add-service=libvirt --permanent
+        # Use dnsmasq as dns in network manager config
+        if ! grep -iqR dns=dnsmasq /etc/NetworkManager/conf.d/ ; then
+        cat << EOF | sudo tee /etc/NetworkManager/conf.d/crc-snc-nm-dnsmasq.conf
+        [main]
+        dns=dnsmasq
+        EOF
+        fi
+
+        # Clean up old DNS overlay file
+        if [ -f /etc/NetworkManager/dnsmasq.d/openshift.conf ]; then
+        sudo rm /etc/NetworkManager/dnsmasq.d/openshift.conf
+        fi
+
+        # Set NetworkManager DNS overlay file
+        cat << EOF | sudo tee /etc/NetworkManager/dnsmasq.d/crc-snc.conf
+        server=/${CRC_VM_NAME}.${BASE_DOMAIN}/192.168.126.1
+        address=/apps-${CRC_VM_NAME}.${BASE_DOMAIN}/192.168.126.11
+        EOF
+
+        # Reload the NetworkManager to make DNS overlay effective
+        sudo systemctl reload NetworkManager
+
+        if [[ ${CERT_ROTATION} == "enabled" ]]
+        then
+            # Disable the network time sync and set the clock to past (for a day) on host
+            sudo timedatectl set-ntp off
+            sudo date -s '-1 day'
+        fi
+
         cd ~
         export OPENSHIFT_VERSION="4.6.40"
         curl -L -o openshift-client-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$${OPENSHIFT_VERSION}/openshift-client-linux.tar.gz
         tar -zxf openshift-client-linux.tar.gz
         sudo mv $HOME/oc /usr/bin
         sudo ln -s /usr/bin/oc /usr/bin/kubectl
-        NAME="mycluster"
-        sudo systemctl stop firewalld # nip.io requires stop firewalld
-        sudo systemctl disable firewalld
-        CLUSTER_DIR="$${HOME}/clusters/$${NAME}"
+
+        #sudo systemctl stop firewalld # nip.io requires stop firewalld
+        #sudo systemctl disable firewalld
         if [ -d "$${CLUSTER_DIR}" ]; then
           echo "WARNING: cluster $${NAME} already exists at $${CLUSTER_DIR}"
         else
@@ -312,8 +341,6 @@
         if [ ! -f $SSH_KEY ]; then
           ssh-keygen -t rsa -N "" -f $SSH_KEY
         fi
-        export BASE_DOMAIN=openshift.testing
-        export CLUSTER_NAME="$${NAME}"
         export PUB_SSH_KEY="$${SSH_KEY}.pub"
         PULL_SECRET=$(cat "$${HOME}/pull-secret.txt")
         cat > "$${CLUSTER_DIR}/install-config.yaml" << EOF
@@ -366,13 +393,16 @@
         cat <<EOF > install.sh
         set -exuo pipefail
         openshift-install create cluster --dir="$CLUSTER_DIR" || true
+        if [[ ${CERT_ROTATION} == "enabled" ]]
+        then
+            renew_certificates
+        fi
         openshift-install wait-for install-complete --dir="$CLUSTER_DIR"
         sudo virsh list --all --name | xargs -L1 sudo virsh autostart
         export SSH="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/crcuser/.ssh/id_rsa"
         export CLUSTER_NAME=$CLUSTER_NAME
         export BASE_DOMAIN=$BASE_DOMAIN
         source /tmp/tools.sh
-        #renew_certificates
         EOF
         chmod +x install.sh
       become: yes
